# Copyright (c) 2023, AgiBot Inc.
# All rights reserved.

if(NOT DEFINED AIMRT_DDS_CODEGEN_MANIFEST)
  message(FATAL_ERROR "AIMRT_DDS_CODEGEN_MANIFEST is required")
endif()

include("${AIMRT_DDS_CODEGEN_MANIFEST}")

function(aimrt_dds_codegen_fail REASON)
  file(REMOVE_RECURSE "${AIMRT_DDS_STAGING_DIR}")
  file(GLOB AIMRT_DDS_STAGING_REMAINDER "${AIMRT_DDS_OUTPUT_DIR}/.aimrt-codegen-staging/*")
  if(NOT AIMRT_DDS_STAGING_REMAINDER)
    file(REMOVE_RECURSE "${AIMRT_DDS_OUTPUT_DIR}/.aimrt-codegen-staging")
  endif()
  message(FATAL_ERROR "${REASON}")
endfunction()

file(REMOVE_RECURSE "${AIMRT_DDS_STAGING_DIR}")
file(GLOB AIMRT_DDS_STAGING_REMAINDER "${AIMRT_DDS_OUTPUT_DIR}/.aimrt-codegen-staging/*")
if(NOT AIMRT_DDS_STAGING_REMAINDER)
  file(REMOVE_RECURSE "${AIMRT_DDS_OUTPUT_DIR}/.aimrt-codegen-staging")
endif()
file(MAKE_DIRECTORY "${AIMRT_DDS_STAGING_DIR}")

execute_process(
  COMMAND "${AIMRT_DDS_FASTDDSGEN_EXECUTABLE}" -replace -flat-output-dir -d "${AIMRT_DDS_STAGING_DIR}" "${AIMRT_DDS_ROOT_IDL}" -no-dependencies ${AIMRT_DDS_FASTDDSGEN_INCLUDE_ARGS}
          ${AIMRT_DDS_FASTDDSGEN_XTYPES_ARGS}
  RESULT_VARIABLE AIMRT_DDS_FASTDDSGEN_RESULT
  OUTPUT_VARIABLE AIMRT_DDS_FASTDDSGEN_STDOUT
  ERROR_VARIABLE AIMRT_DDS_FASTDDSGEN_STDERR)
if(NOT AIMRT_DDS_FASTDDSGEN_RESULT EQUAL 0)
  aimrt_dds_codegen_fail("Fast DDS-Gen failed (${AIMRT_DDS_FASTDDSGEN_RESULT}) for ${AIMRT_DDS_ROOT_IDL}:\n${AIMRT_DDS_FASTDDSGEN_STDOUT}${AIMRT_DDS_FASTDDSGEN_STDERR}")
endif()

execute_process(
  COMMAND ${AIMRT_DDS_RPC_GEN_COMMAND} --idl "${AIMRT_DDS_ROOT_IDL}" --output-dir "${AIMRT_DDS_STAGING_DIR}" --depfile "${AIMRT_DDS_STAGING_DEPFILE}" --root-only
          ${AIMRT_DDS_RPC_INCLUDE_ARGS}
  RESULT_VARIABLE AIMRT_DDS_RPC_RESULT
  OUTPUT_VARIABLE AIMRT_DDS_RPC_STDOUT
  ERROR_VARIABLE AIMRT_DDS_RPC_STDERR)
if(NOT AIMRT_DDS_RPC_RESULT EQUAL 0)
  aimrt_dds_codegen_fail("AimRT DDS RPC generator failed (${AIMRT_DDS_RPC_RESULT}) for ${AIMRT_DDS_ROOT_IDL}:\n${AIMRT_DDS_RPC_STDOUT}${AIMRT_DDS_RPC_STDERR}")
endif()

list(LENGTH AIMRT_DDS_PUBLISH_SOURCES AIMRT_DDS_PUBLISH_SOURCE_COUNT)
list(LENGTH AIMRT_DDS_PUBLISH_DESTINATIONS AIMRT_DDS_PUBLISH_DESTINATION_COUNT)
if(NOT AIMRT_DDS_PUBLISH_SOURCE_COUNT EQUAL AIMRT_DDS_PUBLISH_DESTINATION_COUNT)
  aimrt_dds_codegen_fail("DDS codegen publish manifest has mismatched source and destination counts")
endif()

list(LENGTH AIMRT_DDS_INCLUDE_BASENAMES AIMRT_DDS_INCLUDE_BASENAME_COUNT)
list(LENGTH AIMRT_DDS_INCLUDE_PATHS AIMRT_DDS_INCLUDE_PATH_COUNT)
if(NOT AIMRT_DDS_INCLUDE_BASENAME_COUNT EQUAL AIMRT_DDS_INCLUDE_PATH_COUNT)
  aimrt_dds_codegen_fail("DDS codegen include rewrite manifest has mismatched basename and path counts")
endif()

set(AIMRT_DDS_REWRITTEN_DIR "${AIMRT_DDS_STAGING_DIR}/.rewritten")
file(MAKE_DIRECTORY "${AIMRT_DDS_REWRITTEN_DIR}")

if(AIMRT_DDS_PUBLISH_SOURCE_COUNT GREATER 0)
  math(EXPR AIMRT_DDS_PUBLISH_LAST_INDEX "${AIMRT_DDS_PUBLISH_SOURCE_COUNT} - 1")
  foreach(AIMRT_DDS_PUBLISH_INDEX RANGE ${AIMRT_DDS_PUBLISH_LAST_INDEX})
    list(GET AIMRT_DDS_PUBLISH_SOURCES ${AIMRT_DDS_PUBLISH_INDEX} AIMRT_DDS_PUBLISH_SOURCE)
    if(NOT EXISTS "${AIMRT_DDS_PUBLISH_SOURCE}")
      aimrt_dds_codegen_fail("DDS codegen expected output is missing: ${AIMRT_DDS_PUBLISH_SOURCE}")
    endif()
    file(READ "${AIMRT_DDS_PUBLISH_SOURCE}" AIMRT_DDS_GENERATED_CONTENT)
    if(AIMRT_DDS_INCLUDE_BASENAME_COUNT GREATER 0)
      math(EXPR AIMRT_DDS_INCLUDE_LAST_INDEX "${AIMRT_DDS_INCLUDE_BASENAME_COUNT} - 1")
      foreach(AIMRT_DDS_INCLUDE_INDEX RANGE ${AIMRT_DDS_INCLUDE_LAST_INDEX})
        list(GET AIMRT_DDS_INCLUDE_BASENAMES ${AIMRT_DDS_INCLUDE_INDEX} AIMRT_DDS_INCLUDE_BASENAME)
        list(GET AIMRT_DDS_INCLUDE_PATHS ${AIMRT_DDS_INCLUDE_INDEX} AIMRT_DDS_INCLUDE_PATH)
        string(REPLACE "#include \"${AIMRT_DDS_INCLUDE_BASENAME}\"" "#include \"${AIMRT_DDS_INCLUDE_PATH}\"" AIMRT_DDS_GENERATED_CONTENT "${AIMRT_DDS_GENERATED_CONTENT}")
      endforeach()
    endif()
    string(REGEX MATCHALL "#[ \t]*include[ \t]*\"[^\"/]+\\.(h|hpp|ipp)\"" AIMRT_DDS_BARE_INCLUDES "${AIMRT_DDS_GENERATED_CONTENT}")
    set(AIMRT_DDS_UNMAPPED_INCLUDES)
    foreach(AIMRT_DDS_BARE_INCLUDE IN LISTS AIMRT_DDS_BARE_INCLUDES)
      string(REGEX REPLACE "^#[ \t]*include[ \t]*\"([^\"]+)\"$" "\\1" AIMRT_DDS_BARE_BASENAME "${AIMRT_DDS_BARE_INCLUDE}")
      list(FIND AIMRT_DDS_INCLUDE_BASENAMES "${AIMRT_DDS_BARE_BASENAME}" AIMRT_DDS_BARE_INCLUDE_INDEX)
      if(AIMRT_DDS_BARE_INCLUDE_INDEX EQUAL -1)
        list(APPEND AIMRT_DDS_UNMAPPED_INCLUDES "${AIMRT_DDS_BARE_INCLUDE}")
      endif()
    endforeach()
    if(AIMRT_DDS_UNMAPPED_INCLUDES)
      list(REMOVE_DUPLICATES AIMRT_DDS_UNMAPPED_INCLUDES)
      list(SORT AIMRT_DDS_UNMAPPED_INCLUDES)
      string(JOIN ", " AIMRT_DDS_UNMAPPED_INCLUDE_LIST ${AIMRT_DDS_UNMAPPED_INCLUDES})
      aimrt_dds_codegen_fail("DDS generated include cannot be mapped uniquely in ${AIMRT_DDS_PUBLISH_SOURCE}: ${AIMRT_DDS_UNMAPPED_INCLUDE_LIST}")
    endif()
    set(AIMRT_DDS_REWRITTEN_SOURCE "${AIMRT_DDS_REWRITTEN_DIR}/${AIMRT_DDS_PUBLISH_INDEX}")
    file(WRITE "${AIMRT_DDS_REWRITTEN_SOURCE}" "${AIMRT_DDS_GENERATED_CONTENT}")
    list(APPEND AIMRT_DDS_REWRITTEN_SOURCES "${AIMRT_DDS_REWRITTEN_SOURCE}")
  endforeach()

  foreach(AIMRT_DDS_PUBLISH_INDEX RANGE ${AIMRT_DDS_PUBLISH_LAST_INDEX})
    list(GET AIMRT_DDS_REWRITTEN_SOURCES ${AIMRT_DDS_PUBLISH_INDEX} AIMRT_DDS_REWRITTEN_SOURCE)
    list(GET AIMRT_DDS_PUBLISH_DESTINATIONS ${AIMRT_DDS_PUBLISH_INDEX} AIMRT_DDS_PUBLISH_DESTINATION)
    get_filename_component(AIMRT_DDS_PUBLISH_DIRECTORY "${AIMRT_DDS_PUBLISH_DESTINATION}" DIRECTORY)
    file(MAKE_DIRECTORY "${AIMRT_DDS_PUBLISH_DIRECTORY}")
    execute_process(
      COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${AIMRT_DDS_REWRITTEN_SOURCE}" "${AIMRT_DDS_PUBLISH_DESTINATION}"
      RESULT_VARIABLE AIMRT_DDS_PUBLISH_RESULT
      ERROR_VARIABLE AIMRT_DDS_PUBLISH_ERROR)
    if(NOT AIMRT_DDS_PUBLISH_RESULT EQUAL 0)
      aimrt_dds_codegen_fail("DDS codegen publish failed for ${AIMRT_DDS_PUBLISH_DESTINATION}: ${AIMRT_DDS_PUBLISH_ERROR}")
    endif()
  endforeach()
endif()

get_filename_component(AIMRT_DDS_DEPFILE_DIRECTORY "${AIMRT_DDS_FINAL_DEPFILE}" DIRECTORY)
file(MAKE_DIRECTORY "${AIMRT_DDS_DEPFILE_DIRECTORY}")
execute_process(
  COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${AIMRT_DDS_STAGING_DEPFILE}" "${AIMRT_DDS_FINAL_DEPFILE}"
  RESULT_VARIABLE AIMRT_DDS_DEPFILE_RESULT
  ERROR_VARIABLE AIMRT_DDS_DEPFILE_ERROR)
if(NOT AIMRT_DDS_DEPFILE_RESULT EQUAL 0)
  aimrt_dds_codegen_fail("DDS codegen depfile publish failed: ${AIMRT_DDS_DEPFILE_ERROR}")
endif()

file(REMOVE_RECURSE "${AIMRT_DDS_STAGING_DIR}")
